//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discovery.Console.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:www-infosupport-com:wsdiscovery-demo", ConfigurationName="ServiceReference1.Oracle")]
    public interface Oracle {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:www-infosupport-com:wsdiscovery-demo/Oracle/Ask", ReplyAction="urn:www-infosupport-com:wsdiscovery-demo/Oracle/AskResponse")]
        string Ask(string question);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:www-infosupport-com:wsdiscovery-demo/Oracle/Ask", ReplyAction="urn:www-infosupport-com:wsdiscovery-demo/Oracle/AskResponse")]
        System.Threading.Tasks.Task<string> AskAsync(string question);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OracleChannel : Discovery.Console.ServiceReference1.Oracle, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OracleClient : System.ServiceModel.ClientBase<Discovery.Console.ServiceReference1.Oracle>, Discovery.Console.ServiceReference1.Oracle {
        
        public OracleClient() {
        }
        
        public OracleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OracleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OracleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OracleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Ask(string question) {
            return base.Channel.Ask(question);
        }
        
        public System.Threading.Tasks.Task<string> AskAsync(string question) {
            return base.Channel.AskAsync(question);
        }
    }
}
