//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscoveryDemo.Client.MagicOracleService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:www-infosupport-com:discovery-demo", ConfigurationName="MagicOracleService.IMagicOracle")]
    public interface IMagicOracle {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:www-infosupport-com:discovery-demo/IMagicOracle/Answer", ReplyAction="urn:www-infosupport-com:discovery-demo/IMagicOracle/AnswerResponse")]
        string Answer(string question);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:www-infosupport-com:discovery-demo/IMagicOracle/Answer", ReplyAction="urn:www-infosupport-com:discovery-demo/IMagicOracle/AnswerResponse")]
        System.Threading.Tasks.Task<string> AnswerAsync(string question);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMagicOracleChannel : DiscoveryDemo.Client.MagicOracleService.IMagicOracle, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MagicOracleClient : System.ServiceModel.ClientBase<DiscoveryDemo.Client.MagicOracleService.IMagicOracle>, DiscoveryDemo.Client.MagicOracleService.IMagicOracle {
        
        public MagicOracleClient() {
        }
        
        public MagicOracleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MagicOracleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MagicOracleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MagicOracleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Answer(string question) {
            return base.Channel.Answer(question);
        }
        
        public System.Threading.Tasks.Task<string> AnswerAsync(string question) {
            return base.Channel.AnswerAsync(question);
        }
    }
}
